from pydantic import BaseModel

class FrameRequest(BaseModel):
    blue_team_total_gold: int
    blue_team_inhibitors: int
    blue_team_towers: int
    blue_team_barons: int
    blue_team_total_kills: int
    blue_team_ocean_drakes: int
    blue_team_cloud_drakes: int
    blue_team_mountain_drakes: int
    blue_team_chemtech_drakes: int
    blue_team_infernal_drakes: int
    blue_team_hextech_drakes: int
    blue_team_elder_drakes: int
    blue_top_total_gold: int
    blue_top_level: int
    blue_top_kills: int
    blue_top_deaths: int
    blue_top_assists: int
    blue_top_creep_score: int
    blue_top_current_health: int
    blue_top_max_health: int
    blue_jungle_total_gold: int
    blue_jungle_level: int
    blue_jungle_kills: int
    blue_jungle_deaths: int
    blue_jungle_assists: int
    blue_jungle_creep_score: int
    blue_jungle_current_health: int
    blue_jungle_max_health: int
    blue_mid_total_gold: int
    blue_mid_level: int
    blue_mid_kills: int
    blue_mid_deaths: int
    blue_mid_assists: int
    blue_mid_creep_score: int
    blue_mid_current_health: int
    blue_mid_max_health: int
    blue_bot_total_gold: int
    blue_bot_level: int
    blue_bot_kills: int
    blue_bot_deaths: int
    blue_bot_assists: int
    blue_bot_creep_score: int
    blue_bot_current_health: int
    blue_bot_max_health: int
    blue_supp_total_gold: int
    blue_supp_level: int
    blue_supp_kills: int
    blue_supp_deaths: int
    blue_supp_assists: int
    blue_supp_creep_score: int
    blue_supp_current_health: int
    blue_supp_max_health: int
    red_team_total_gold: int
    red_team_inhibitors: int
    red_team_towers: int
    red_team_barons: int
    red_team_total_kills: int
    red_team_ocean_drakes: int
    red_team_cloud_drakes: int
    red_team_mountain_drakes: int
    red_team_chemtech_drakes: int
    red_team_infernal_drakes: int
    red_team_hextech_drakes: int
    red_team_elder_drakes: int
    red_top_total_gold: int
    red_top_level: int
    red_top_kills: int
    red_top_deaths: int
    red_top_assists: int
    red_top_creep_score: int
    red_top_current_health: int
    red_top_max_health: int
    red_jungle_total_gold: int
    red_jungle_level: int
    red_jungle_kills: int
    red_jungle_deaths: int
    red_jungle_assists: int
    red_jungle_creep_score: int
    red_jungle_current_health: int
    red_jungle_max_health: int
    red_mid_total_gold: int
    red_mid_level: int
    red_mid_kills: int
    red_mid_deaths: int
    red_mid_assists: int
    red_mid_creep_score: int
    red_mid_current_health: int
    red_mid_max_health: int
    red_bot_total_gold: int
    red_bot_level: int
    red_bot_kills: int
    red_bot_deaths: int
    red_bot_assists: int
    red_bot_creep_score: int
    red_bot_current_health: int
    red_bot_max_health: int
    red_supp_total_gold: int
    red_supp_level: int
    red_supp_kills: int
    red_supp_deaths: int
    red_supp_assists: int
    red_supp_creep_score: int
    red_supp_current_health: int
    red_supp_max_health: int
    blue_top_champ: int
    red_top_champ: int
    blue_jungle_champ: int
    red_jungle_champ: int
    blue_mid_champ: int
    red_mid_champ: int
    blue_bot_champ: int
    red_bot_champ: int
    blue_supp_champ: int
    red_supp_champ: int
    time_in_game: int